function [fitresult, gof] = createFit(t, y, m)
%CREATEFIT(T,Y,M)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Input : y
%      Z Output: m
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Mar-2016 17:32:29


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( t, y, m );

% Set up fittype and options.
ft = fittype( 'b*exp(-x/a)+y', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.849129305868777 0.933993247757551];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'm vs. t, y', 'Location', 'NorthEast' );
% % Label axes
% xlabel t
% ylabel y
% zlabel m
% grid on
% view( 11.7, -25.2 );


